
name: Go Test/Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build & Test
        run: make build && make test

      - name: Setup Prereqs
        run: sudo apt-get install -y alien

      - name: Build Installer
        run: sudo make build-deb

      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
            name: debian-build
            path: build/rcagent_*.deb

  build_centos_el9:
    runs-on: ubuntu-latest
    container:
      image: tgagor/centos:stream9
    steps:
      - uses: actions/checkout@v3

      - name: Install Prereqs
        run: yum install golang rpm-build systemd-rpm-macros make -y

      - name: Build & Test
        run: make build && make test

      - name: Build Installer
        run: make build-rpm

      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
            name: centos-build-el9
            path: build/rcagent-*.rpm

  build_centos_el8:
    runs-on: ubuntu-latest
    container:
      image: tgagor/centos:stream8
    steps:
      - uses: actions/checkout@v3

      - name: Install Prereqs
        run: yum install golang rpm-build systemd-rpm-macros make -y

      - name: Build & Test
        run: make build && make test

      - name: Build Installer
        run: make build-rpm

      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
            name: centos-build-el8
            path: build/rcagent-*.rpm

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build & Test
        run: make build && make test

      - name: Build Installer
        run: |
          LDFLAGS="-X github.com/rechecked/rcagent/internal/config.PluginDir=/usr/local/rcagent/plugins \
          -X github.com/rechecked/rcagent/internal/config.ConfigDir=/etc/rcagnet" \
          make build && make build-dmg

      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
            name: macos-build
            path: build/rcagent-*.dmg

  build_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build & Test
        run: go build -v && go test -v ./...

      - name: Set path for candle and light
        run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
        shell: bash

      - name: Build Installer
        run: build/build_windows.bat ${GITHUB_SHA::6}

      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
            name: windows-build
            path: build/rcagent-install.msi
