
name: Go Test/Build

on:
  push:

jobs:

  build_ubuntu22:
    runs-on: ubuntu-latest
    steps:
      - name: Submit Version Change
        run: |
          curl --request GET 'https://api.rechecked.io/versions?product=rcagent&action=set_latest&version=$GITHUB_REF_NAME&api_key=${{ secrets.RECHECKED_API_KEY }}'

